apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: tanzu-development
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
spec:
  owner: default-team
